### PR TITLE
Several fixes, mostly around parsing new Messages

### PR DESCRIPTION
**Pull request by nanomad**

### CODE REVIEW

**Review by 0liv1er — CHANGES_REQUESTED** [review]
This commit breaks the original file format https://github.com/0liv1er/omci-wireshark-dissector/pull/2/commits/5e3a6f1d744a63e7af2a116043bae098fd96f0ea

**Review by 0liv1er — CHANGES_REQUESTED** [review]
This commit is unneccessary for the dissector and won't be merged https://github.com/0liv1er/omci-wireshark-dissector/pull/2/commits/6dba654ef7d64c0771545879ddc7de6bb6dfb6ac

**Review by 0liv1er — CHANGES_REQUESTED** [review]
This commit also breaks the original file format
https://github.com/0liv1er/omci-wireshark-dissector/pull/2/commits/26be7f0d8b921e3fd8e4cb37c9ade17da96a6f5e

**Comment by nanomad** [comment]
> This commit also breaks the original file format

I'm sorry but I don't see what commits you're referring to. If you could share the commit ID I'll try to address the issues

**Comment by 0liv1er** [comment]
> > This commit also breaks the original file format
> 
> I'm sorry but I don't see what commits you're referring to. If you could share the commit ID I'll try to address the issues

comments updated with commit number

**Comment by simonebortolin** [comment]
> comments updated with commit number

fixed

**Pull request merged**
